# Tarea para el Hogar 04 (Ejecución Local)
## Optimización de Hiperparámetros en LightGBM

### 1. Overfitting the Public Leaderboard
Lectura recomendada: https://medium.com/hmif-itb/overfitting-the-leaderboard-da25172ac62e

### 2. Objetivos
* Aumentar la rentabilidad de la campaña de marketing de retención proactiva de clientes.
* Generar un mejor modelo optimizando sus hiperparámetros.
* Conceptual: investigar los más relevantes hiperparámetros de LightGBM.
* Ver y ejecutar un pipeline completo de optimización de hiperparámetros y puesta en producción en entorno local.

#### 2.1 Seteo del ambiente local
Configuración de directorios de trabajo y verificación/descarga del dataset localmente.

In [1]:
# Determinar la raíz del proyecto (dmeyf2026) de forma robusta
find_project_root <- function() {
  curr <- normalizePath(getwd(), winslash = "/")
  while (curr != "/" && curr != dirname(curr)) {
    if (basename(curr) == "dmeyf2026" || (dir.exists(file.path(curr, "src")) && dir.exists(file.path(curr, "src", "ensembles")))) {
      return(curr)
    }
    curr <- dirname(curr)
  }
  if (dir.exists(file.path(getwd(), "dmeyf2026"))) {
    return(normalizePath(file.path(getwd(), "dmeyf2026"), winslash = "/"))
  }
  if (dir.exists("/home/sectorial/data-mining/dmeyf2026")) {
    return("/home/sectorial/data-mining/dmeyf2026")
  }
  return(normalizePath(getwd(), winslash = "/"))
}

dir_base <- find_project_root()
setwd(dir_base)
cat("Raíz del proyecto (dmeyf2026):", dir_base, "\n")

# Configurar entorno para proxy y herramientas CLI (Kaggle)
Sys.setenv(
  http_proxy = "http://10.4.8.20:8080",
  https_proxy = "http://10.4.8.20:8080",
  HTTP_PROXY = "http://10.4.8.20:8080",
  HTTPS_PROXY = "http://10.4.8.20:8080",
  PATH = paste("/home/sectorial/anaconda3/bin", file.path(Sys.getenv("HOME"), ".local/bin"), Sys.getenv("PATH"), sep = ":")
)

# Crear carpetas locales para datasets y experimentos dentro de dmeyf2026
dir.create(file.path(dir_base, "datasets"), showWarnings = FALSE, recursive = TRUE)
dir.create(file.path(dir_base, "exp"), showWarnings = FALSE, recursive = TRUE)

# Descargar el dataset si no existe localmente en dmeyf2026/datasets
url_dataset <- "https://storage.googleapis.com/open-courses/utn2026-b40a/dataset_pequeno.csv"
archivo_dataset <- file.path(dir_base, "datasets", "dataset_pequeno.csv")

if (!file.exists(archivo_dataset)) {
  cat("Descargando dataset_pequeno.csv en", archivo_dataset, "...\n")
  download.file(url_dataset, destfile = archivo_dataset, mode = "wb")
  cat("Descarga completada exitosamente.\n")
} else {
  cat("El dataset ya se encuentra disponible en:", archivo_dataset, "\n")
}

Raíz del proyecto (dmeyf2026): /workspace/dmeyf2026
El dataset ya se encuentra disponible en: /workspace/dmeyf2026/datasets/dataset_pequeno.csv

### 2.2 Optimización de Hiperparámetros
#### 2.2.1 Inicio y limpieza de memoria

In [2]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Fri Aug 28 19:27:34 2026"

In [3]:
# limpio la memoria
rm(list = ls(all.names = TRUE)) # remove all objects
gc(full = TRUE, verbose = FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  661963 35.4 1454514    77.7 1454514  77.7
Vcells 1232934  9.5 8388608    64.0 1975054  15.1

#### 2.2.2 Carga de Librerías

In [4]:
# Cargo librerías requeridas (instalando automáticamente si no existen)
if (!require("data.table")) install.packages("data.table", repos = "https://cloud.r-project.org")
require("data.table")

if (!require("parallel")) install.packages("parallel", repos = "https://cloud.r-project.org")
require("parallel")

if (!require("primes")) install.packages("primes", repos = "https://cloud.r-project.org")
require("primes")

if (!require("utils")) install.packages("utils", repos = "https://cloud.r-project.org")
require("utils")

if (!require("rlist")) install.packages("rlist", repos = "https://cloud.r-project.org")
require("rlist")

if (!require("yaml")) install.packages("yaml", repos = "https://cloud.r-project.org")
require("yaml")

if (!require("lightgbm")) install.packages("lightgbm", repos = "https://cloud.r-project.org")
require("lightgbm")

Loading required package: data.table

Loading required package: parallel

Loading required package: primes

Loading required package: rlist

Loading required package: yaml

Loading required package: lightgbm

#### 2.2.3 Definición de Parámetros
Aquí se debe configurar su semilla primigenia y el número de experimento.

In [5]:
PARAM <- list()
PARAM$experimento <- '494_02_BIS'
PARAM$semilla_primigenia <- 115879 # Reemplazar con su semilla primigenia si corresponde

PARAM$kaggle$competencia <- "utn-2026-inicial"
PARAM$kaggle$cortes <- seq(9000, 12000, by = 500)

# Estrategia de entrenamiento: undersampling de los CONTINUA
# 0.5 toma el 50% de los CONTINUA y 100% de BAJA+1 y BAJA+2
PARAM$trainingstrategy$undersampling <- 0.5

# Folds para Cross-Validation
PARAM$hyperparametertuning$xval_folds <- 5

# Parámetros fijos del LightGBM que se pisarán con la parte variable de la búsqueda
PARAM$lgbm$param_fijos <- list(
  boosting = "gbdt",
  objective = "binary",
  metric = "auc",
  first_metric_only = FALSE,
  boost_from_average = TRUE,
  feature_pre_filter = FALSE,
  force_row_wise = TRUE, # para reducir warnings
  verbosity = -100,

  seed = PARAM$semilla_primigenia,

  max_depth = -1L, # -1 significa no limitar la profundidad
  min_gain_to_split = 0,
  min_sum_hessian_in_leaf = 0.001,
  lambda_l1 = 0.0,
  lambda_l2 = 0.0,
  max_bin = 31L,

  bagging_fraction = 1.0,
  pos_bagging_fraction = 1.0,
  neg_bagging_fraction = 1.0,
  is_unbalance = FALSE,
  scale_pos_weight = 1.0,

  drop_rate = 0.1,
  max_drop = 50,
  skip_drop = 0.5,

  extra_trees = FALSE,

  num_iterations = 100,
  learning_rate = 0.10,
  feature_fraction = 1.0,
  num_leaves = 32,
  min_data_in_leaf = 20
)

#### 2.2.4 Preprocesamiento y Creación del Dataset de Entrenamiento

In [6]:
# Determinar la raíz del proyecto (dmeyf2026) de forma robusta
find_project_root <- function() {
  curr <- normalizePath(getwd(), winslash = "/")
  while (curr != "/" && curr != dirname(curr)) {
    if (basename(curr) == "dmeyf2026" || (dir.exists(file.path(curr, "src")) && dir.exists(file.path(curr, "src", "ensembles")))) {
      return(curr)
    }
    curr <- dirname(curr)
  }
  if (dir.exists(file.path(getwd(), "dmeyf2026"))) {
    return(normalizePath(file.path(getwd(), "dmeyf2026"), winslash = "/"))
  }
  if (dir.exists("/home/sectorial/data-mining/dmeyf2026")) {
    return("/home/sectorial/data-mining/dmeyf2026")
  }
  return(normalizePath(getwd(), winslash = "/"))
}

dir_base <- find_project_root()
experimento_folder <- paste0("HT", PARAM$experimento)
dir_exp <- file.path(dir_base, "exp", experimento_folder)
dir.create(dir_exp, showWarnings = FALSE, recursive = TRUE)
setwd(dir_exp)
cat("Directorio de trabajo actual:", getwd(), "\n")

Directorio de trabajo actual: /workspace/dmeyf2026/exp/HT494_02_BIS

In [7]:
# Lectura del dataset local
archivo_dataset <- file.path(dir_base, "datasets", "dataset_pequeno.csv")
dataset <- fread(archivo_dataset)

# Filtrar mes de entrenamiento (202107)
dataset_train <- dataset[foto_mes %in% c(202107)]

# Paso la clase a binaria {0, 1}: BAJA+1 y BAJA+2 son 1, CONTINUA es 0
dataset_train[, clase01 := ifelse(clase_ternaria %in% c("BAJA+2", "BAJA+1"), 1L, 0L)]

# Undersampling de los CONTINUA usando la semilla primigenia
set.seed(PARAM$semilla_primigenia, kind = "L'Ecuyer-CMRG")
dataset_train[, azar := runif(nrow(dataset_train))]
dataset_train[, training := 0L]
dataset_train[
  foto_mes %in% c(202107) &
    (azar <= PARAM$trainingstrategy$undersampling | clase_ternaria %in% c("BAJA+1", "BAJA+2")),
  training := 1L
]

# Campos a utilizar
campos_buenos <- setdiff(
  colnames(dataset_train),
  c("clase_ternaria", "clase01", "azar", "training")
)

# Crear estructura lgb.Dataset
dtrain <- lgb.Dataset(
  data = data.matrix(dataset_train[training == 1L, campos_buenos, with = FALSE]),
  label = dataset_train[training == 1L, clase01],
  free_raw_data = FALSE
)

cat("Registros para CV (con undersampling):", nrow(dtrain), "| Columnas:", ncol(dtrain), "\n")

Registros para CV (con undersampling): 83081 | Columnas: 154

#### 2.2.5 Configuración y Ejecución del Grid Search

In [8]:
# Función que estima el AUC en Cross-Validation de 5 folds para un vector de hiperparámetros 'x'
Estimar_AUC_lightgbm <- function(x) {
  # x pisa o agrega a param_fijos
  param_completo <- modifyList(PARAM$lgbm$param_fijos, x)

  # entreno LightGBM con validación cruzada
  modelocv <- lgb.cv(
    data = dtrain,
    nfold = PARAM$hyperparametertuning$xval_folds,
    stratified = TRUE,
    param = param_completo
  )

  # obtengo la mejor métrica (AUC)
  AUC <- modelocv$best_score

  # libero memoria
  rm(modelocv)
  gc(full = TRUE, verbose = FALSE)

  message(format(Sys.time(), "%a %b %d %X %Y  "),
    toString(x),
    " AUC ", AUC
  )

  return(AUC)
}

In [12]:
# Definir el producto cartesiano de hiperparámetros a explorar
# Aquí usted puede experimentar agregando/modificando los valores y parámetros

# Configuración por defecto
# tb_nueva <- CJ(
#   num_iterations = c(100, 500, 1000),
#   learning_rate = c(0.02, 0.05, 0.1),
#   num_leaves = c(10, 50, 100, 500)
# )

# Experimento 594_00
# tb_nueva <- CJ(
#   learning_rate    = c(0.02, 0.05),
#   num_leaves       = c(50, 80, 120),
#   min_data_in_leaf = c(200, 500),
#   feature_fraction = c(0.4, 0.7),
#   num_iterations   = c(300, 600, 1000)
# )

# Experimento 594_01
# tb_nueva <- CJ(
#   learning_rate    = c(0.01, 0.04),
#   num_leaves       = c(50, 80, 120, 200),
#   min_data_in_leaf = c(100, 200, 500, 1000),
#   feature_fraction = c(0.5, 0.6, 0.7),
#   num_iterations   = c(300, 600, 1000)
# )

# Experimento no realizado, dio mismo óptimo que el anterior
# tb_nueva <- CJ(
#   learning_rate    = c(0.01,0.02,0.03,0.04),
#   num_leaves       = c(50, 120, 400, 600),
#   min_data_in_leaf = c(100, 200, 500, 1000),
#   feature_fraction = c(0.5, 0.6, 0.7),
#   num_iterations   = c(300, 600, 1000)
# )

# Experimento 494_02
tb_nueva <- CJ(
  learning_rate    = c(0.015, 0.025, 0.035),
  num_leaves       = c(90, 140, 200),
  min_data_in_leaf = c(150, 300),
  feature_fraction = c(0.30, 0.40, 0.50),
  num_iterations   = c(500, 700)
)


cat("Cantidad total de combinaciones a evaluar:", nrow(tb_nueva), "\n")
tb_nueva

Cantidad total de combinaciones a evaluar: 108

    learning_rate num_leaves min_data_in_leaf feature_fraction num_iterations
1   0.015          90        150              0.3              500
2   0.015          90        150              0.3              700
3   0.015          90        150              0.4              500
4   0.015          90        150              0.4              700
5   0.015          90        150              0.5              500
6   0.015          90        150              0.5              700
7   0.015          90        300              0.3              500
8   0.015          90        300              0.3              700
9   0.015          90        300              0.4              500
10  0.015          90        300              0.4              700
11  0.015          90        300              0.5              500
12  0.015          90        300              0.5              700
13  0.015         140        150              0.3              500
14  0.015         140        150              0.3              700
15  0.015         140        150              0.4              500
16  0.015         140        150              0.4              700
17  0.015         140        150              0.5              500
18  0.015         140        150              0.5              700
19  0.015         140        300              0.3              500
20  0.015         140        300              0.3              700
21  0.015         140        300              0.4              500
22  0.015         140        300              0.4              700
23  0.015         140        300              0.5              500
24  0.015         140        300              0.5              700
25  0.015         200        150              0.3              500
26  0.015         200        150              0.3              700
27  0.015         200        150              0.4              500
28  0.015         200        150              0.4              700
29  0.015         200        150              0.5              500
30  0.015         200        150              0.5              700
⋮   ⋮             ⋮          ⋮                ⋮                ⋮
79  0.035          90        300              0.3              500
80  0.035          90        300              0.3              700
81  0.035          90        300              0.4              500
82  0.035          90        300              0.4              700
83  0.035          90        300              0.5              500
84  0.035          90        300              0.5              700
85  0.035         140        150              0.3              500
86  0.035         140        150              0.3              700
87  0.035         140        150              0.4              500
88  0.035         140        150              0.4              700
89  0.035         140        150              0.5              500
90  0.035         140        150              0.5              700
91  0.035         140        300              0.3              500
92  0.035         140        300              0.3              700
93  0.035         140        300              0.4              500
94  0.035         140        300              0.4              700
95  0.035         140        300              0.5              500
96  0.035         140        300              0.5              700
97  0.035         200        150              0.3              500
98  0.035         200        150              0.3              700
99  0.035         200        150              0.4              500
100 0.035         200        150              0.4              700
101 0.035         200        150              0.5              500
102 0.035         200        150              0.5              700
103 0.035         200        300              0.3              500
104 0.035         200        300              0.3              700
105 0.035         200        300              0.4              500
106 0.035         200        300              0.4              700
107 0.035         200        300              0.5              500
108 0.035         200        300              0.5              700

In [10]:
# Registro a registro calculo la AUC en Cross-Validation
tb_nueva[, AUC := Estimar_AUC_lightgbm(list(.SD)), by = 1:nrow(tb_nueva)]

# Mostrar resultados ordenados
setorder(tb_nueva, -AUC)
tb_nueva

Fri Aug 28 19:27:43 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 300) AUC 0.925893460664036

Fri Aug 28 19:27:52 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 600) AUC 0.924973964875888

Fri Aug 28 19:28:00 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 1000) AUC 0.926631616313201

Fri Aug 28 19:28:07 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 300) AUC 0.925268741275167

Fri Aug 28 19:28:14 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 600) AUC 0.925317751186717

Fri Aug 28 19:28:19 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 1000) AUC 0.925873578603952

Fri Aug 28 19:28:27 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 300) AUC 0.926707233436348

Fri Aug 28 19:28:33 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 600) AUC 0.92670759291981

Fri Aug 28 19:28:39 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 1000) AUC 0.924365299056784

Fri Aug 28 19:28:45 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 300) AUC 0.926353077555699

Fri Aug 28 19:28:52 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 600) AUC 0.925649421318558

Fri Aug 28 19:28:56 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 1000) AUC 0.924743995155653

Fri Aug 28 19:29:03 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 300) AUC 0.925702102758177

Fri Aug 28 19:29:07 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 600) AUC 0.925132167823485

Fri Aug 28 19:29:12 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 1000) AUC 0.926060010463524

Fri Aug 28 19:29:17 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 300) AUC 0.925018726878919

Fri Aug 28 19:29:24 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 600) AUC 0.925777100006859

Fri Aug 28 19:29:30 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 1000) AUC 0.926443942153628

Fri Aug 28 19:29:38 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 300) AUC 0.925007945112173

Fri Aug 28 19:29:44 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 600) AUC 0.925748597801058

Fri Aug 28 19:29:49 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 1000) AUC 0.925979641683861

Fri Aug 28 19:29:53 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 300) AUC 0.925930721290552

Fri Aug 28 19:29:58 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 600) AUC 0.924518128896789

Fri Aug 28 19:30:02 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 1000) AUC 0.925437192158561

Fri Aug 28 19:30:07 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 300) AUC 0.925413219357293

Fri Aug 28 19:30:11 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 600) AUC 0.92808302732527

Fri Aug 28 19:30:15 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 1000) AUC 0.925612926855479

Fri Aug 28 19:30:19 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 300) AUC 0.926481839633192

Fri Aug 28 19:30:23 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 600) AUC 0.923683794039678

Fri Aug 28 19:30:27 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 1000) AUC 0.925092779242431

Fri Aug 28 19:30:31 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 300) AUC 0.925337895524504

Fri Aug 28 19:30:36 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 600) AUC 0.925414980311281

Fri Aug 28 19:30:40 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 1000) AUC 0.924736137423397

Fri Aug 28 19:30:44 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 300) AUC 0.924984454287048

Fri Aug 28 19:30:48 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 600) AUC 0.9262451605964

Fri Aug 28 19:30:52 2026  list(learning_rate = 0.01, num_leaves = 50, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 1000) AUC 0.925528247264944

Fri Aug 28 19:30:56 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 300) AUC 0.924264412490647

Fri Aug 28 19:31:00 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 600) AUC 0.92574190541881

Fri Aug 28 19:31:04 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 1000) AUC 0.924171024016236

Fri Aug 28 19:31:09 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 300) AUC 0.926592196359223

Fri Aug 28 19:31:13 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 600) AUC 0.926028996522924

Fri Aug 28 19:31:17 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 1000) AUC 0.92469185253747

Fri Aug 28 19:31:21 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 300) AUC 0.926957084441129

Fri Aug 28 19:31:25 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 600) AUC 0.925448288376191

Fri Aug 28 19:31:29 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 1000) AUC 0.925726658612494

Fri Aug 28 19:31:33 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 300) AUC 0.925379809549863

Fri Aug 28 19:31:37 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 600) AUC 0.926760055117046

Fri Aug 28 19:31:41 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 1000) AUC 0.925971890589383

Fri Aug 28 19:31:45 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 300) AUC 0.925332967021955

Fri Aug 28 19:31:49 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 600) AUC 0.925218237945388

Fri Aug 28 19:31:53 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 1000) AUC 0.925783061677954

Fri Aug 28 19:31:57 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 300) AUC 0.925168721469686

Fri Aug 28 19:32:02 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 600) AUC 0.926714392498404

Fri Aug 28 19:32:06 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 1000) AUC 0.926388285990871

Fri Aug 28 19:32:10 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 300) AUC 0.924657145826612

Fri Aug 28 19:32:13 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 600) AUC 0.926015482242204

Fri Aug 28 19:32:17 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 1000) AUC 0.925182471018818

Fri Aug 28 19:32:21 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 300) AUC 0.926348211621625

Fri Aug 28 19:32:26 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 600) AUC 0.925899424169131

Fri Aug 28 19:32:30 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 1000) AUC 0.924843614984916

Fri Aug 28 19:32:34 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 300) AUC 0.925288369706547

Fri Aug 28 19:32:38 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 600) AUC 0.925374727778756

Fri Aug 28 19:32:42 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 1000) AUC 0.925646421071944

Fri Aug 28 19:32:46 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 300) AUC 0.927364438503191

Fri Aug 28 19:32:49 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 600) AUC 0.924537978444183

Fri Aug 28 19:32:54 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 1000) AUC 0.926217451760103

Fri Aug 28 19:32:57 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 300) AUC 0.924092559579809

Fri Aug 28 19:33:01 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 600) AUC 0.925837515551725

Fri Aug 28 19:33:05 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 1000) AUC 0.926019241158537

Fri Aug 28 19:33:09 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 300) AUC 0.925062575160828

Fri Aug 28 19:33:13 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 600) AUC 0.926326788034834

Fri Aug 28 19:33:17 2026  list(learning_rate = 0.01, num_leaves = 120, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 1000) AUC 0.925582895027917

Fri Aug 28 19:33:21 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 300) AUC 0.926113935470663

Fri Aug 28 19:33:25 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 600) AUC 0.925265487110569

Fri Aug 28 19:33:28 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 1000) AUC 0.925239066261883

Fri Aug 28 19:33:32 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 300) AUC 0.926493401103232

Fri Aug 28 19:33:36 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 600) AUC 0.924012965750505

Fri Aug 28 19:33:40 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 1000) AUC 0.926132973736399

Fri Aug 28 19:33:45 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 300) AUC 0.926279545138178

Fri Aug 28 19:33:49 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 600) AUC 0.926511179148321

Fri Aug 28 19:33:52 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 1000) AUC 0.925745425957543

Fri Aug 28 19:33:56 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 300) AUC 0.924969531429628

Fri Aug 28 19:34:00 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 600) AUC 0.925540313791835

Fri Aug 28 19:34:03 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 1000) AUC 0.926557547698675

Fri Aug 28 19:34:07 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 300) AUC 0.925371047660392

Fri Aug 28 19:34:11 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 600) AUC 0.926323770198357

Fri Aug 28 19:34:15 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 1000) AUC 0.925676234555464

Fri Aug 28 19:34:19 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 300) AUC 0.926742177024007

Fri Aug 28 19:34:23 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 600) AUC 0.925370933121113

Fri Aug 28 19:34:27 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 200, feature_fraction = 0.7, num_iterations = 1000) AUC 0.926671603025575

Fri Aug 28 19:34:31 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 300) AUC 0.926406529508322

Fri Aug 28 19:34:34 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 600) AUC 0.925575868992248

Fri Aug 28 19:34:39 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.5, num_iterations = 1000) AUC 0.925803715060228

Fri Aug 28 19:34:43 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 300) AUC 0.92424674086231

Fri Aug 28 19:34:47 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 600) AUC 0.926773561371962

Fri Aug 28 19:34:51 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.6, num_iterations = 1000) AUC 0.924832874174071

Fri Aug 28 19:34:55 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 300) AUC 0.925907505158874

Fri Aug 28 19:34:59 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 600) AUC 0.926091254099163

Fri Aug 28 19:35:03 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 500, feature_fraction = 0.7, num_iterations = 1000) AUC 0.924707451398515

Fri Aug 28 19:35:07 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 300) AUC 0.926177744590676

Fri Aug 28 19:35:11 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 600) AUC 0.926189541977766

Fri Aug 28 19:35:15 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.5, num_iterations = 1000) AUC 0.92650476892963

Fri Aug 28 19:35:19 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 300) AUC 0.926021914635402

Fri Aug 28 19:35:22 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 600) AUC 0.926407932337512

Fri Aug 28 19:35:26 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.6, num_iterations = 1000) AUC 0.925696894558244

Fri Aug 28 19:35:30 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 300) AUC 0.925421589952199

Fri Aug 28 19:35:34 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 600) AUC 0.924758145997669

Fri Aug 28 19:35:39 2026  list(learning_rate = 0.01, num_leaves = 400, min_data_in_leaf = 1000, feature_fraction = 0.7, num_iterations = 1000) AUC 0.926051762167358

Fri Aug 28 19:35:43 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 300) AUC 0.92499189164278

Fri Aug 28 19:35:46 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 600) AUC 0.92598631579338

Fri Aug 28 19:35:50 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.5, num_iterations = 1000) AUC 0.923838162974529

Fri Aug 28 19:35:54 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 300) AUC 0.925944886001338

Fri Aug 28 19:35:58 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 600) AUC 0.925542995319855

Fri Aug 28 19:36:03 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.6, num_iterations = 1000) AUC 0.9261860760032

Fri Aug 28 19:36:07 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 300) AUC 0.924539530970496

Fri Aug 28 19:36:11 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 600) AUC 0.924760513555304

Fri Aug 28 19:36:14 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 100, feature_fraction = 0.7, num_iterations = 1000) AUC 0.925232832031742

Fri Aug 28 19:36:18 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 300) AUC 0.926173793313426

Fri Aug 28 19:36:22 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 600) AUC 0.925964632969846

Fri Aug 28 19:36:26 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 200, feature_fraction = 0.5, num_iterations = 1000) AUC 0.927412927534701

Fri Aug 28 19:36:31 2026  list(learning_rate = 0.01, num_leaves = 600, min_data_in_leaf = 200, feature_fraction = 0.6, num_iterations = 300) AUC 0.924800464413023


    learning_rate num_leaves min_data_in_leaf feature_fraction num_iterations
1   0.01           50         500             0.7               600
2   0.02          400         500             0.5              1000
3   0.04          400         100             0.7               300
4   0.01          600        1000             0.6              1000
5   0.01          600         200             0.5              1000
6   0.01          120        1000             0.5               300
7   0.03           50         500             0.5               600
8   0.02           50         200             0.6               300
9   0.03           50         200             0.5               600
10  0.02          120         200             0.5               300
11  0.04          600         200             0.5               600
12  0.04           50        1000             0.6               600
13  0.02          600        1000             0.6              1000
14  0.03          400         100             0.6               600
15  0.03          120         200             0.6               600
16  0.04          120         100             0.7               300
17  0.03          400         100             0.6              1000
18  0.03          120         500             0.6               600
19  0.04          600        1000             0.5               300
20  0.02          600         100             0.7               300
21  0.01          120         100             0.7               300
22  0.03           50         100             0.7               300
23  0.02          600         200             0.5               300
24  0.03          400         100             0.7               600
25  0.04          600         500             0.7              1000
26  0.03          120         100             0.5               300
27  0.04          600         100             0.5               300
28  0.03           50         100             0.5              1000
29  0.03          600        1000             0.7               300
30  0.04          120         200             0.7               300
⋮   ⋮             ⋮          ⋮                ⋮                ⋮
547 0.03          400        1000             0.5               300
548 0.03          400        1000             0.7               600
549 0.02          600         200             0.6               600
550 0.01           50         100             0.7              1000
551 0.04          600        1000             0.7               600
552 0.01          600        1000             0.5               300
553 0.04          600        1000             0.6              1000
554 0.02           50         500             0.7               300
555 0.03          120         200             0.6              1000
556 0.01          120         100             0.5               300
557 0.01          400         500             0.6               300
558 0.01          120         100             0.5              1000
559 0.04           50         500             0.5               600
560 0.02           50        1000             0.7               600
561 0.04          400        1000             0.6               600
562 0.01          120        1000             0.6               300
563 0.01          600         500             0.6               300
564 0.04          600         100             0.6              1000
565 0.01          400         100             0.6               600
566 0.02           50         500             0.6               300
567 0.03          600         100             0.7               600
568 0.01          600         500             0.6              1000
569 0.03          600         200             0.7              1000
570 0.01          600         100             0.5              1000
571 0.02           50         200             0.5               600
572 0.04          400         500             0.6               300
573 0.04          600         100             0.7               600
574 0.01           50        1000             0.5               600
575 0.04          120         500             0.6              1000
576 0.04          400         100             0.5              1000
    AUC
1   0.9280830
2   0.9275099
3   0.9275048
4   0.9274907
5   0.9274129
6   0.9273644
7   0.9273295
8   0.9273116
9   0.9272804
10  0.9272263
11  0.9272018
12  0.9271533
13  0.9271519
14  0.9270946
15  0.9270807
16  0.9270792
17  0.9270637
18  0.9270252
19  0.9269958
20  0.9269797
21  0.9269571
22  0.9269105
23  0.9269102
24  0.9268934
25  0.9268722
26  0.9268654
27  0.9268635
28  0.9268420
29  0.9268416
30  0.9268318
⋮   ⋮
547 0.9244090
548 0.9244009
549 0.9243791
550 0.9243653
551 0.9243612
552 0.9243336
553 0.9243187
554 0.9243022
555 0.9242982
556 0.9242644
557 0.9242467
558 0.9241710
559 0.9241622
560 0.9241553
561 0.9241071
562 0.9240926
563 0.9240746
564 0.9240505
565 0.9240130
566 0.9239963
567 0.9239527
568 0.9239113
569 0.9238762
570 0.9238382
571 0.9237930
572 0.9237758
573 0.9237586
574 0.9236838
575 0.9236551
576 0.9234484

In [11]:
# Grabar tabla con los resultados del Grid Search
fwrite(tb_nueva,
  file = "tb_grid_search_01.txt",
  sep = "\t",
  append = TRUE
)

# Guardar los mejores hiperparámetros en PARAM
PARAM$out$lgbm$AUC <- tb_nueva[1, AUC]
PARAM$out$lgbm$mejores_hiperparametros <- as.list(tb_nueva[1])
PARAM$out$lgbm$mejores_hiperparametros$AUC <- NULL

cat("Mejor AUC obtenida:", PARAM$out$lgbm$AUC, "\n")
cat("Mejores hiperparámetros:\n")
print(PARAM$out$lgbm$mejores_hiperparametros)

# Guardar PARAM en YAML
write_yaml(PARAM, file = "PARAM.yml")

Mejor AUC obtenida: 0.928083
Mejores hiperparámetros:
$learning_rate
[1] 0.01

$num_leaves
[1] 50

$min_data_in_leaf
[1] 500

$feature_fraction
[1] 0.7

$num_iterations
[1] 600

## 2.3 Producción / Final Training
Construyo el modelo final con los mejores hiperparámetros encontrados, entrenando sobre TODOS los datos de `202107` (sin undersampling) y ajustando `min_data_in_leaf`.

### 2.4 Scoring y Generación de Envíos a Kaggle
Aplico el modelo a los datos del futuro (`foto_mes == 202109`) y genero los archivos de corte.

### 2.5 Registro en la Google Sheet Colaborativa
Cargue los resultados de su corrida en la Google Sheet Colaborativa, en la hoja **`TareaHogar-04`**:
* Número de experimento
* Semilla utilizada
* Mejores hiperparámetros encontrados y su AUC en Cross-Validation
* Ganancias en Kaggle para los distintos puntos de corte (9.000 a 12.000)